#!/usr/bin/env node
// Generates lib/build-info.ts with the running build's identity:
//   buildId   — short git SHA (or 'dev' / 'unknown' fallbacks)
//   buildName — adjective-animal codename derived deterministically
//               from buildId, so the same commit always gets the same
//               name on every machine (dev, CI, Pi).
//   buildTime — ISO timestamp when this script ran.
//
// Inputs, in priority order:
//   1. $BUILD_SHA  — set by CI (Docker build-arg → ENV)
//   2. `git rev-parse --short HEAD` — local dev with a git checkout
//   3. literal 'dev' — no git available (tarball install, etc.)
//
// Output file is gitignored; it's regenerated on postinstall, predev,
// and prebuild so any entry point produces a valid artifact.

import { execSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const repoRoot = resolve(dirname(__filename), '..')
const outputPath = resolve(repoRoot, 'lib/build-info.ts')

const ADJECTIVES = [
  'breezy', 'cosmic', 'dapper', 'eager', 'fluffy', 'glowing', 'happy', 'jolly',
  'kindly', 'lucky', 'mellow', 'nimble', 'peppy', 'quirky', 'radiant', 'snazzy',
  'tidy', 'upbeat', 'vivid', 'wacky', 'zesty', 'brave', 'calm', 'curious',
  'dreamy', 'electric', 'fancy', 'gentle', 'hearty', 'jazzy', 'keen', 'lively',
  'merry', 'noble', 'plucky', 'regal', 'silly', 'tame', 'witty', 'sunny',
]

const ANIMALS = [
  'axolotl', 'badger', 'capybara', 'dolphin', 'ermine', 'ferret', 'gecko',
  'hedgehog', 'ibex', 'jackalope', 'koala', 'lemur', 'manatee', 'narwhal',
  'otter', 'panda', 'quokka', 'raccoon', 'sloth', 'tapir', 'urial', 'vole',
  'walrus', 'xerus', 'yak', 'zebu', 'alpaca', 'beaver', 'chinchilla', 'dingo',
  'elk', 'fennec', 'gerbil', 'hamster', 'iguana', 'jellyfish', 'kiwi', 'llama',
  'mongoose', 'numbat',
]

// FNV-1a 32-bit. Deterministic, no crypto needed — we're picking from
// 40-item lists, not securing anything.
function fnv1a(str) {
  let hash = 0x811c9dc5
  for (let i = 0; i < str.length; i++) {
    hash ^= str.charCodeAt(i)
    hash = (hash * 0x01000193) >>> 0
  }
  return hash
}

function codenameFor(seed) {
  // Two separate hashes (seed + salt) so adjective and animal don't
  // correlate with each other across small seed changes.
  const a = fnv1a(`${seed}:adjective`) % ADJECTIVES.length
  const n = fnv1a(`${seed}:animal`) % ANIMALS.length
  return `${ADJECTIVES[a]}-${ANIMALS[n]}`
}

function resolveBuildId() {
  const fromEnv = process.env.BUILD_SHA?.trim()
  if (fromEnv) return fromEnv.slice(0, 7)

  try {
    return execSync('git rev-parse --short HEAD', {
      cwd: repoRoot,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim()
  } catch {
    // No git available — tarball install, Docker without .git, etc.
    // Returning 'dev' keeps the codename stable across dev runs so the
    // About page doesn't churn while you're hacking on it.
    return 'dev'
  }
}

const buildId = resolveBuildId()
const buildName = codenameFor(buildId)
const buildTime = new Date().toISOString()

const content = `// AUTO-GENERATED by scripts/build-info.mjs — DO NOT EDIT.
// Regenerated on postinstall / predev / prebuild.

export const buildInfo = {
  buildId: ${JSON.stringify(buildId)},
  buildName: ${JSON.stringify(buildName)},
  buildTime: ${JSON.stringify(buildTime)},
} as const

export type BuildInfo = typeof buildInfo
`

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, content)
console.log(`[build-info] ${buildName} (${buildId}) — ${buildTime}`)
